### ekf config file ###
ekf_filter_node:
    ros__parameters:
        frequency: 10.0
        two_d_mode: true
        publish_tf: true

        map_frame: map              # Defaults to "map" if unspecified
        odom_frame: odom            # Defaults to "odom" if unspecified
        base_link_frame: base_link  # Defaults to "base_link" if unspecified
        world_frame: map           # Defaults to the value of odom_frame if unspecified

# Mecanum Controller's Odometry
        odom0: odom
        odom0_config: [true,  true,  false,
                       false, false, true,
                       true, true, false,
                       false, false, true,
                       false, false, false]
        odom0_differential: false

# SSL_SLAM's Odometry from scan matcher
        odom1: laser_odom
        odom1_config: [true, true, false,
                       false, false, true,
                       false, false, false,
                       false, false, false,
                       false, false, false]
        odom1_differential: false
